smoia/phys2cvr

phys2cvr/io.py, phys2cvr/phys2cvr.py
=> Fix outputs paths and names

phys2cvr/cli/run.py, phys2cvr/phys2cvr.py
=> Fix denoise_matrix input from CLI that was causing it to be a list of lists

phys2cvr/io.py
=> Fixed output regressor to be the optimally shifted version, rather than the original demeaned regressor

phys2cvr/cli/run.py, phys2cvr/phys2cvr.py
=> If scale factor is declared, *divide* the betas by the scale factor

phys2cvr/phys2cvr.py
=> Fix peak array loading for index purposes

phys2cvr/phys2cvr.py
=> Fix scale factor (divide instead of multiply) for bulk shift output

phys2cvr/phys2cvr.py
=> Add output of all regression results for debug

phys2cvr/phys2cvr.py
Fix #28 (@kristinazvolanek have a look here ;) )
-
-
-
=> Fix astype call on physiological indexes array

phys2cvr/cli/run.py, phys2cvr/phys2cvr.py, phys2cvr/stats.py
Closes None but fixes `stats.regression` and adds a bunch of options.
Edits to regression function to match outputs of AFNI's 3dDeconvolve and an equivalent implementation of OLS regression in R.
On top of that, added options to select r2 model for regression step.
Possible models are "full", "intercept", or "partial" - and adjusted versions of.
- `stats.regression` now behaves as expected - removed possible coding mistakes.
- parser accepts various r2 models
- parser object check sets r2model to 'full' if it's None
- main workflow and stats.regression take r2model as parameter: they set the r2model to use.
- `stats.R2MODEL` contains supported r2models.
=> Updated regression function

phys2cvr/phys2cvr.py, phys2cvr/stats.py
Closes #
Forces all created matrices to be float32 to avoid numerical errors.
-
-
-
=> Force all empty matrices to be float32

phys2cvr/cli/run.py, phys2cvr/io.py, phys2cvr/phys2cvr.py, phys2cvr/signal.py, phys2cvr/stats.py
Closes #
- Fix various bugs int he fmri-only workflow
- Add a signal percentage change function in signal (`signal.spc`)
- Add a resampling function in signal (`signal.resample_signal`)
- `io.export_regressor` now requires frequency and tr as input, opposed to previous time length arrays.
=> Fix workflow to estimate CVR from fMRI only

phys2cvr/phys2cvr.py
=> Fix if statement for skipping convolution

phys2cvr/phys2cvr.py, phys2cvr/signal.py
=> Fix SPC computation by dividing by the transposed mean (not the matrix itself)

phys2cvr/signal.py
=> Let signal be resampled over any axis of the input timeseries (default to first dimension)

phys2cvr/cli/run.py, phys2cvr/phys2cvr.py, phys2cvr/stats.py
Closes #
- Cross correlation can shift both petco2hrf and func_avg
- Cross correlation can be absolutised before choosing its maximum point (default is not to)
-
=> Enhance cross correlation to allow both regressor and reference to be shifted and consider max abs corr

phys2cvr/phys2cvr.py, phys2cvr/stats.py
=> Allow confounding matrix and mask to be optional in `stats.regression`

phys2cvr/cli/run.py, phys2cvr/phys2cvr.py, phys2cvr/stats.py
=> Add the possibility to skip the cross correlation step when creating lagged regressors

phys2cvr/phys2cvr.py
Closes #51 
Fix error on 4d volume input.
-
-
-
=> Fix dimensionality check for functional images

phys2cvr/cli/run.py
=> Check English in the CLI

phys2cvr/signal.py, phys2cvr/stats.py
=> Check english and clarify docstrings

phys2cvr/tests/test_io.py
=> test functions for io module
